server:
  port: 8090
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bookee.bookee.entity
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/pmsdev?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

